### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-scunet#5]
After installing latest vs-dpir I installed vs-scunet which didn't show any errors on installation, but when trying to use it crashes.
[vapoursynth_editor_log_2023-05-21_20-23-44-278.zip](https://github.com/HolyWu/vs-scunet/files/11525274/vapoursynth_editor_log_2023-05-21_20-23-44-278.zip)
Would be nice if you could fix this. Thanks!

**Comment by HolyWu** [comment]
nvfuser (which uses `functorch.compile` underlying) is not supported as of PyTorch 2.0. They suggest using `torch.compile()` instead, but unfortunately it's not yet supported for Windows.

**Comment by Selur** [comment]
Thanks for looking into it. Works fine without fusion. 👍
